networks:
  hosting:
    external: true

services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    restart: unless-stopped
    ports:
      - 33334:80
    # environment:
    #   - PUID=1000
    #   - PGID=1000
    user: 1000:1000
    volumes:
      - /mnt/files/Mediaserver/Anime:/srv/Anime
      - /mnt/files/Mediaserver/Movies:/srv/Movies
      - /mnt/files/Mediaserver/Shows:/srv/Shows
      - /mnt/files/Filebrowser/${uni}:/srv/${uni}
      - /mnt/files/Filebrowser/_private:/srv/_private
      - ./data/torrents:/srv/Torrents

      # - ./config/filebrowser/settings.json:/config/settings.json
      # - ./data/filebrowser/filebrowser.db:/database/filebrowser.db

      - ./data/filebrowser/database.db:/database.db
      - ./config/filebrowser/filebrowser.json:/.filebrowser.json

      #
      # - ./data/filebrowser/database.db:/database.db
      # - ./data/filebrowser/filebrowser.db:/database/filebrowser.db
      # - ./data/filebrowser/.filebrowser.json:/.filebrowser.json
    networks:
      - hosting
