networks:
  default:
  dbs_postgres:
    external: true
  hosting:
    external: true

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: unless-stopped
    environment:
      - USER_ID=${UID}
      - USER_GID=${GUID}
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=postgres_gitea:${POSTGRES_PORT}
      - GITEA__database__NAME=${POSTGRES_DB}
      - GITEA__database__USER=${POSTGRES_USER}
      - GITEA__database__PASSWD=${POSTGRES_PASSWORD}
    volumes:
      - ./data/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 10000:3000
      - 222:22
    networks:
      - default
      - hosting
    depends_on:
      - postgres_gitea

  postgres_gitea:
    image: postgres:14
    container_name: postgres_gitea
    restart: unless-stopped
    environment:
      - PGPORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
        - default
        - dbs_postgres
