networks:
  internal:
  dbs_postgres:
    external: true

services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    restart: unless-stopped
    container_name: speedtest_tracker
    ports:
      - 38080:80
      - 38081:443
    environment:
      - PUID=1000
      - PGID=1000
      - APP_TIMEZONE=${TZ}
      - DISPLAY_TIMEZONE=${TZ}
      - APP_KEY=${APP_KEY}
      - SPEEDTEST_SCHEDULE=0 5 * * *
      - DB_CONNECTION=pgsql
      - DB_HOST=speedtest_db
      - DB_PORT=5432
      - DB_DATABASE=${PG_DB}
      - DB_USERNAME=${PG_USER}
      - DB_PASSWORD=${PG_PASS}
    volumes:
      - ./config/speedtest_tracker/config:/config
      - ./config/speedtest_tracker/keys:/config/keys
    depends_on:
      - speedtest_db
    networks:
      - internal

  speedtest_db:
    image: postgres:17
    restart: always
    container_name: speedtest_db
    environment:
      - TZ=${TZ}
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 5
      timeout: 5s
    networks:
      - internal
      - dbs_postgres
